#ifndef GOOGLE_APIS_INTERNAL_METRICS_SIGNING_KEY_H_
#define GOOGLE_APIS_INTERNAL_METRICS_SIGNING_KEY_H_

// 留空即可：表示不使用官方遥测签名，禁用向 Google 上报指标日志签名
#define GOOGLE_METRICS_SIGNING_KEY ""

#endif  // GOOGLE_APIS_INTERNAL_METRICS_SIGNING_KEY_H_